name: test
on:
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    container: golang:1.22

    steps:
      - uses: actions/checkout@v4
      - name: Set up Go 1.22
        uses: actions/setup-go@v4
        with:
          go-version: 1.22
      - name: Run tests
        env:
          APP_ENV: test
          APP_DEBUG: true
          DB_PORT: 3306
          DB_DATABASE: intospaceapi
          DB_HOST: mysql
          DB_USERNAME: root
          DB_PASSWORD: root
          MIGRATIONS_PATH: /__w/intospaceapi/intospaceapi/migrations
        run: |
          echo ${GITHUB_WORKSPACE} && CGO_ENALBED=0 GOOS=linux go test -v -race -coverprofile=coverage.txt ./...